
microscope:
  name:
    'PPM'

stage:
  z_stage:
    'ZStage'
  xlimit: 
    low: 33000.0 
    high: -21000.0
  ylimit: 
    low: -8000.0  
    high: 11000.0
  zlimit: 
    low: 0.0
    high: 0.0
  vendor: Prior

imagingMode:
  BF_10x:
    isLSM : false
    objectiveLens: LOCI-10x-001
    pixelSize_um : 0.4537
    pixelOffset:
      x: 0
      y: 0
    stageoffset:
      z: 0
      f: 0
    objectivePositionLabel: ~
    lampIntensity_V: ~
    detector: LOCI-CAMERA-002
  BF_20x:
    isLSM : false
    objectiveLens: LOCI-20x-002
    pixelSize_um : 0.2271
    pixelOffset:
      x: 0
      y: 0
    stageoffset:
      z: 0
      f: 0
    objectivePositionLabel: ~
    lampIntensity_V: ~
    detector: LOCI-CAMERA-002
  BF_40x:
    isLSM : false    
    pixelSize_um : 0.1142
    pixelOffset:
      x: 0
      y: 0
    stageoffset:
      z: 0
      f: 0
    objectivePositionLabel: ~
    lampIntensity_V: ~
    detector: LOCI-CAMERA-002
    objectiveLens: LOCI-40x-001 

slideSize:
  x: 40000
  y: 20000